name: Deploy Task Scheduler

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted      # Runs on YOUR Windows machine

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Update and Deploy Task Scheduler
        run: |
          cd /home/subaru/projects/Task-Schedular/Multi-Threading-Task_Schedular
          git fetch origin
          git reset --hard origin/main
          sg docker -c "docker build -t taskscheduler:latest ."
          sg docker -c "docker stop taskscheduler || true"
          sg docker -c "docker rm taskscheduler || true"
          sg docker -c "docker run -d --name taskscheduler -p 8081:8081 taskscheduler:latest"
          sg docker -c "docker image prune -a -f --filter 'until=24h'"

      - name: Verify container is running
        run: |
          status=$(docker inspect --format="{{.State.Status}}" taskscheduler)
          if [ "$status" != "running" ]; then
            echo "TaskScheduler container is NOT running. Status: $status"
            exit 1
          fi
          echo "TaskScheduler container is running successfully."
